//
// Attribute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Attribute: Codable {

    public var _id: Int?
    public var _description: String?
    public var attribute: String?
    public var expression: String?
    /** String|Number|Boolean */
    public var type: String?

    public init(_id: Int?, _description: String?, attribute: String?, expression: String?, type: String?) {
        self._id = _id
        self._description = _description
        self.attribute = attribute
        self.expression = expression
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case _description = "description"
        case attribute
        case expression
        case type
    }


}

