//
// Calendar.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Calendar: Codable {

    public var _id: Int?
    public var name: String?
    /** base64 encoded in iCalendar format */
    public var data: String?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, name: String?, data: String?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.name = name
        self.data = data
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case data
        case attributes
    }


}

