//
// Device.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Device: Codable {

    public var _id: Int?
    public var name: String?
    public var uniqueId: String?
    public var status: String?
    public var disabled: Bool?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var lastUpdate: Date?
    public var positionId: Int?
    public var groupId: Int?
    public var phone: String?
    public var model: String?
    public var contact: String?
    public var category: String?
    public var geofenceIds: [Int]?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, name: String?, uniqueId: String?, status: String?, disabled: Bool?, lastUpdate: Date?, positionId: Int?, groupId: Int?, phone: String?, model: String?, contact: String?, category: String?, geofenceIds: [Int]?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.name = name
        self.uniqueId = uniqueId
        self.status = status
        self.disabled = disabled
        self.lastUpdate = lastUpdate
        self.positionId = positionId
        self.groupId = groupId
        self.phone = phone
        self.model = model
        self.contact = contact
        self.category = category
        self.geofenceIds = geofenceIds
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case uniqueId
        case status
        case disabled
        case lastUpdate
        case positionId
        case groupId
        case phone
        case model
        case contact
        case category
        case geofenceIds
        case attributes
    }


}

