//
// DeviceAccumulators.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceAccumulators: Codable {

    public var deviceId: Int?
    /** in meters */
    public var totalDistance: Double?
    public var hours: Double?

    public init(deviceId: Int?, totalDistance: Double?, hours: Double?) {
        self.deviceId = deviceId
        self.totalDistance = totalDistance
        self.hours = hours
    }


}

