//
// Driver.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Driver: Codable {

    public var _id: Int?
    public var name: String?
    public var uniqueId: String?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, name: String?, uniqueId: String?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.name = name
        self.uniqueId = uniqueId
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case uniqueId
        case attributes
    }


}

