//
// Event.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Event: Codable {

    public var _id: Int?
    public var type: String?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var serverTime: Date?
    public var deviceId: Int?
    public var positionId: Int?
    public var geofenceId: Int?
    public var maintenanceId: Int?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, type: String?, serverTime: Date?, deviceId: Int?, positionId: Int?, geofenceId: Int?, maintenanceId: Int?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.type = type
        self.serverTime = serverTime
        self.deviceId = deviceId
        self.positionId = positionId
        self.geofenceId = geofenceId
        self.maintenanceId = maintenanceId
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case serverTime
        case deviceId
        case positionId
        case geofenceId
        case maintenanceId
        case attributes
    }


}

