//
// Geofence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Geofence: Codable {

    public var _id: Int?
    public var name: String?
    public var _description: String?
    public var area: String?
    public var calendarId: Int?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, name: String?, _description: String?, area: String?, calendarId: Int?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.name = name
        self._description = _description
        self.area = area
        self.calendarId = calendarId
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case area
        case calendarId
        case attributes
    }


}

