//
// Maintenance.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Maintenance: Codable {

    public var _id: Int?
    public var name: String?
    public var type: String?
    public var start: Double?
    public var period: Double?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, name: String?, type: String?, start: Double?, period: Double?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.name = name
        self.type = type
        self.start = start
        self.period = period
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case type
        case start
        case period
        case attributes
    }


}

