//
// Notification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Notification: Codable {

    public var _id: Int?
    public var type: String?
    public var always: Bool?
    public var web: Bool?
    public var mail: Bool?
    public var sms: Bool?
    public var calendarId: Int?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, type: String?, always: Bool?, web: Bool?, mail: Bool?, sms: Bool?, calendarId: Int?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.type = type
        self.always = always
        self.web = web
        self.mail = mail
        self.sms = sms
        self.calendarId = calendarId
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case always
        case web
        case mail
        case sms
        case calendarId
        case attributes
    }


}

