//
// NotificationType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NotificationType: Codable {

    public var type: String?

    public init(type: String?) {
        self.type = type
    }


}

