//
// Permission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** This is a permission map that contain two object indexes. It is used to link/unlink objects. Order is important. Example: { deviceId:8, geofenceId: 16 } */

public struct Permission: Codable {

    /** User Id, can be only first parameter */
    public var userId: Int?
    /** Device Id, can be first parameter or second only in combination with userId */
    public var deviceId: Int?
    /** Group Id, can be first parameter or second only in combination with userId */
    public var groupId: Int?
    /** Geofence Id, can be second parameter only */
    public var geofenceId: Int?
    /** Calendar Id, can be second parameter only and only in combination with userId */
    public var calendarId: Int?
    /** Computed Attribute Id, can be second parameter only */
    public var attributeId: Int?
    /** Driver Id, can be second parameter only */
    public var driverId: Int?
    /** User Id, can be second parameter only and only in combination with userId */
    public var managedUserId: Int?

    public init(userId: Int?, deviceId: Int?, groupId: Int?, geofenceId: Int?, calendarId: Int?, attributeId: Int?, driverId: Int?, managedUserId: Int?) {
        self.userId = userId
        self.deviceId = deviceId
        self.groupId = groupId
        self.geofenceId = geofenceId
        self.calendarId = calendarId
        self.attributeId = attributeId
        self.driverId = driverId
        self.managedUserId = managedUserId
    }


}

