//
// Position.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Position: Codable {

    public var _id: Int?
    public var deviceId: Int?
    public var _protocol: String?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var deviceTime: Date?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var fixTime: Date?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var serverTime: Date?
    public var outdated: Bool?
    public var valid: Bool?
    public var latitude: Double?
    public var longitude: Double?
    public var altitude: Double?
    /** in knots */
    public var speed: Double?
    public var course: Double?
    public var address: String?
    public var accuracy: Double?
    public var network: [String:JSONValue]?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, deviceId: Int?, _protocol: String?, deviceTime: Date?, fixTime: Date?, serverTime: Date?, outdated: Bool?, valid: Bool?, latitude: Double?, longitude: Double?, altitude: Double?, speed: Double?, course: Double?, address: String?, accuracy: Double?, network: [String:JSONValue]?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.deviceId = deviceId
        self._protocol = _protocol
        self.deviceTime = deviceTime
        self.fixTime = fixTime
        self.serverTime = serverTime
        self.outdated = outdated
        self.valid = valid
        self.latitude = latitude
        self.longitude = longitude
        self.altitude = altitude
        self.speed = speed
        self.course = course
        self.address = address
        self.accuracy = accuracy
        self.network = network
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case deviceId
        case _protocol = "protocol"
        case deviceTime
        case fixTime
        case serverTime
        case outdated
        case valid
        case latitude
        case longitude
        case altitude
        case speed
        case course
        case address
        case accuracy
        case network
        case attributes
    }


}

