//
// ReportStops.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportStops: Codable {

    public var deviceId: Int?
    public var deviceName: String?
    public var duration: Int?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var startTime: Date?
    public var address: String?
    public var lat: Double?
    public var lon: Double?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var endTime: Date?
    /** in liters */
    public var spentFuel: Double?
    public var engineHours: Int?

    public init(deviceId: Int?, deviceName: String?, duration: Int?, startTime: Date?, address: String?, lat: Double?, lon: Double?, endTime: Date?, spentFuel: Double?, engineHours: Int?) {
        self.deviceId = deviceId
        self.deviceName = deviceName
        self.duration = duration
        self.startTime = startTime
        self.address = address
        self.lat = lat
        self.lon = lon
        self.endTime = endTime
        self.spentFuel = spentFuel
        self.engineHours = engineHours
    }


}

