//
// ReportTrips.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportTrips: Codable {

    public var deviceId: Int?
    public var deviceName: String?
    /** in knots */
    public var maxSpeed: Double?
    /** in knots */
    public var averageSpeed: Double?
    /** in meters */
    public var distance: Double?
    /** in liters */
    public var spentFuel: Double?
    public var duration: Int?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var startTime: Date?
    public var startAddress: String?
    public var startLat: Double?
    public var startLon: Double?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var endTime: Date?
    public var endAddress: String?
    public var endLat: Double?
    public var endLon: Double?
    public var driverUniqueId: Int?
    public var driverName: String?

    public init(deviceId: Int?, deviceName: String?, maxSpeed: Double?, averageSpeed: Double?, distance: Double?, spentFuel: Double?, duration: Int?, startTime: Date?, startAddress: String?, startLat: Double?, startLon: Double?, endTime: Date?, endAddress: String?, endLat: Double?, endLon: Double?, driverUniqueId: Int?, driverName: String?) {
        self.deviceId = deviceId
        self.deviceName = deviceName
        self.maxSpeed = maxSpeed
        self.averageSpeed = averageSpeed
        self.distance = distance
        self.spentFuel = spentFuel
        self.duration = duration
        self.startTime = startTime
        self.startAddress = startAddress
        self.startLat = startLat
        self.startLon = startLon
        self.endTime = endTime
        self.endAddress = endAddress
        self.endLat = endLat
        self.endLon = endLon
        self.driverUniqueId = driverUniqueId
        self.driverName = driverName
    }


}

