//
// ReportSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportSummary: Codable {

    public var deviceId: Int?
    public var deviceName: String?
    /** in knots */
    public var maxSpeed: Double?
    /** in knots */
    public var averageSpeed: Double?
    /** in meters */
    public var distance: Double?
    /** in liters */
    public var spentFuel: Double?
    public var engineHours: Int?

    public init(deviceId: Int?, deviceName: String?, maxSpeed: Double?, averageSpeed: Double?, distance: Double?, spentFuel: Double?, engineHours: Int?) {
        self.deviceId = deviceId
        self.deviceName = deviceName
        self.maxSpeed = maxSpeed
        self.averageSpeed = averageSpeed
        self.distance = distance
        self.spentFuel = spentFuel
        self.engineHours = engineHours
    }


}

