//
// Server.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Server: Codable {

    public var _id: Int?
    public var registration: Bool?
    public var readonly: Bool?
    public var deviceReadonly: Bool?
    public var limitCommands: Bool?
    public var map: String?
    public var bingKey: String?
    public var mapUrl: String?
    public var poiLayer: String?
    public var latitude: Double?
    public var longitude: Double?
    public var zoom: Int?
    public var twelveHourFormat: Bool?
    public var version: String?
    public var forceSettings: Bool?
    public var coordinateFormat: String?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, registration: Bool?, readonly: Bool?, deviceReadonly: Bool?, limitCommands: Bool?, map: String?, bingKey: String?, mapUrl: String?, poiLayer: String?, latitude: Double?, longitude: Double?, zoom: Int?, twelveHourFormat: Bool?, version: String?, forceSettings: Bool?, coordinateFormat: String?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.registration = registration
        self.readonly = readonly
        self.deviceReadonly = deviceReadonly
        self.limitCommands = limitCommands
        self.map = map
        self.bingKey = bingKey
        self.mapUrl = mapUrl
        self.poiLayer = poiLayer
        self.latitude = latitude
        self.longitude = longitude
        self.zoom = zoom
        self.twelveHourFormat = twelveHourFormat
        self.version = version
        self.forceSettings = forceSettings
        self.coordinateFormat = coordinateFormat
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case registration
        case readonly
        case deviceReadonly
        case limitCommands
        case map
        case bingKey
        case mapUrl
        case poiLayer
        case latitude
        case longitude
        case zoom
        case twelveHourFormat
        case version
        case forceSettings
        case coordinateFormat
        case attributes
    }


}

