//
// Statistics.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Statistics: Codable {

    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var captureTime: Date?
    public var activeUsers: Int?
    public var activeDevices: Int?
    public var requests: Int?
    public var messagesReceived: Int?
    public var messagesStored: Int?

    public init(captureTime: Date?, activeUsers: Int?, activeDevices: Int?, requests: Int?, messagesReceived: Int?, messagesStored: Int?) {
        self.captureTime = captureTime
        self.activeUsers = activeUsers
        self.activeDevices = activeDevices
        self.requests = requests
        self.messagesReceived = messagesReceived
        self.messagesStored = messagesStored
    }


}

