//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var _id: Int?
    public var name: String?
    public var email: String?
    public var readonly: Bool?
    public var administrator: Bool?
    public var map: String?
    public var latitude: Double?
    public var longitude: Double?
    public var zoom: Int?
    public var password: String?
    public var twelveHourFormat: Bool?
    public var coordinateFormat: String?
    public var disabled: Bool?
    /** in IS0 8601 format. eg. &#x60;1963-11-22T18:30:00Z&#x60; */
    public var expirationTime: Date?
    public var deviceLimit: Int?
    public var userLimit: Int?
    public var deviceReadonly: Bool?
    public var limitCommands: Bool?
    public var poiLayer: String?
    public var token: String?
    public var attributes: [String:JSONValue]?

    public init(_id: Int?, name: String?, email: String?, readonly: Bool?, administrator: Bool?, map: String?, latitude: Double?, longitude: Double?, zoom: Int?, password: String?, twelveHourFormat: Bool?, coordinateFormat: String?, disabled: Bool?, expirationTime: Date?, deviceLimit: Int?, userLimit: Int?, deviceReadonly: Bool?, limitCommands: Bool?, poiLayer: String?, token: String?, attributes: [String:JSONValue]?) {
        self._id = _id
        self.name = name
        self.email = email
        self.readonly = readonly
        self.administrator = administrator
        self.map = map
        self.latitude = latitude
        self.longitude = longitude
        self.zoom = zoom
        self.password = password
        self.twelveHourFormat = twelveHourFormat
        self.coordinateFormat = coordinateFormat
        self.disabled = disabled
        self.expirationTime = expirationTime
        self.deviceLimit = deviceLimit
        self.userLimit = userLimit
        self.deviceReadonly = deviceReadonly
        self.limitCommands = limitCommands
        self.poiLayer = poiLayer
        self.token = token
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case email
        case readonly
        case administrator
        case map
        case latitude
        case longitude
        case zoom
        case password
        case twelveHourFormat
        case coordinateFormat
        case disabled
        case expirationTime
        case deviceLimit
        case userLimit
        case deviceReadonly
        case limitCommands
        case poiLayer
        case token
        case attributes
    }


}

